imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: true

web_profiler:
    toolbar: true
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

donate_core:
    mail:
        donator: true
        webmaster : ['sgogel@ecedi.fr'] ##tableau d'email
    equivalence:
        spot:
            - {amount : 20, label : '20<span class="euro">€</span>', default: true}
            - {amount : 50, label : '50<span class="euro">€</span>'}
            - {amount : 100, label : '100<span class="euro">€</span>'}
        recuring:
            - {amount : 5, label : '5<span class="euro">€</span>'}
            - {amount : 10, label : '10<span class="euro">€</span>'}
            - {amount : 20, label : '20<span class="euro">€</span>'}
    # payment_methods: ['ogone']

donate_front:
    campaign: _utm

doctrine:
    dbal:
        dbname: "%database_name%_test"
