<?php

namespace Ecedi\Donate\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LayoutRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LayoutRepository extends EntityRepository
{
    public function getQb()
    {
        return $this->createQueryBuilder('l');
    }

    protected function defaultLayoutQb()
    {
        $qb = $this->getQb();
        $qb
            ->where('l.isDefault = true')
            ->andWhere('l.language = :language')
            ->add('orderBy', 'l.id ASC');

        return $qb;
    }

    public function getFindAllQuery()
    {
        $qb = $this->getQb();
        $qb
            ->add('orderBy', 'l.isDefault DESC')
        ;

        return $qb->getQuery();
    }

    public function getDefaultLayout($lang = 'fr')
    {
        $qb = $this->defaultLayoutQb();
        $qb->setParameter('language', $lang)
        ;

        return $qb->getQuery()->getSingleResult();
    }

    public function findDefaultLayout($lang = 'fr')
    {
        $qb = $this->defaultLayoutQb();
        $qb->setParameter('language', $lang);

        return $qb->getQuery()->getResult();
    }
}
