<?php

namespace Ecedi\Donate\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
    * Fonction qui retourne tous les utilisateurs
    *
    * @param array $parameters
    * @param integer $limit
    */
    public function getAllUsers()
    {
        $qb = $this->createQueryBuilder('u');

        return $qb->getQuery();
    }

}
